fix: conflict between .eslintrc.json and BaseConfig
npm dedupe && npm i

ERROR: Create-react-app - ERROR in Plugin "react" was conflicted between ".eslintrc.json" and "BaseConfig"